name: Tests

on:
  push:
    paths:
    - "**/*.py"
  pull_request:
    paths:
    - "**/*.py"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: "Set up timezone to America/Los_Angeles"
      uses: actions/set-timezone-action@v1.1
      with:
        timezoneLinux: "America/Los_Angeles"
        timezoneMacos: "America/Los_Angeles"
        timezoneWindows: "America/Los_Angeles"
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with unittest
      run: |
        python -m unittest discover tests
